//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteKeeperWebApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Note
    {
        public int NotesID { get; set; }

        [Display(Name = "Note")]
        public string Note1 { get; set; }
        public Nullable<int> userID { get; set; }
        [Display(Name = "Shared With")]
        public string share { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }

        [Display(Name = "Posted By")]
        public string PostedBy { get; set; }
    
        public virtual UserDetail UserDetail { get; set; }
    }
}
